# $Id: Makefile.config,v 1.1 2001/07/06 19:14:34 cjo Exp $

COMMON_DEFINES = -DABCSP_TEST

MAKEDEFINES=$(COMMON_DEFINES)

.SUFFIXES: $(SUFFIXES)

SHELL = /bin/sh

INCLUDES = -I. -I$(TOP)/abcsp/include -I$(TOP)/abcsp/src -I$(TOP)/abcsp/config

CC = gcc -Wall -Wpointer-arith -Wno-switch
# CC = /opt/SUNWspro/bin/cc
# CFLAGS += -O
CFLAGS += -g
CPPFLAGS += $(MAKEDEFINES) $(INCLUDES)
LINT = /opt/SUNWspro/bin/lint
# LINT = touch
LINTFLAGS = $(XMAKEDEFINES)


LORDER = lorder
TSORT = tsort
RANLIB = touch
MAKEDEPEND = makedepend
CHMOD = chmod
CP = cp
TOUCH = touch
MKDIR = mkdir -p
CAT = cat
MV = mv
